"""

Revision ID: 15b66322ba31
Revises: 
Create Date: 2025-10-09 23:57:53.616288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b66322ba31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('coupon_id', sa.String(length=50), nullable=True),
    sa.Column('offer_description', sa.String(length=255), nullable=True),
    sa.Column('offer_name', sa.String(length=10), nullable=False),
    sa.Column('offer_starts', sa.DateTime(), nullable=False),
    sa.Column('offer_ends', sa.DateTime(), nullable=False),
    sa.Column('discount_percent', sa.String(length=10), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('no_of_items', sa.String(length=20), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price_m', sa.String(length=10), nullable=False),
    sa.Column('price_y', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('products', sa.String(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_plan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['products'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.Column('type_of_merchant', sa.String(), server_default='moderate', nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('mid', sa.String(), nullable=True),
    sa.Column('bin', sa.String(), nullable=True),
    sa.Column('mcc', sa.String(), nullable=True),
    sa.Column('ein', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_user_id'), 'merchants', ['user_id'], unique=False)
    op.create_table('payment_gateways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=False),
    sa.Column('publishable_key', sa.TEXT(), nullable=False),
    sa.Column('webhook', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateways_id'), 'payment_gateways', ['id'], unique=False)
    op.create_index(op.f('ix_payment_gateways_user_id'), 'payment_gateways', ['user_id'], unique=False)
    op.create_table('plan_products',
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'product_id')
    )
    op.create_table('ach_authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('routing', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('authorized_signer', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ach_authorizations_id'), 'ach_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_ach_authorizations_merchant_id'), 'ach_authorizations', ['merchant_id'], unique=False)
    op.create_table('chargebacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('chargeback_code', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargebacks_id'), 'chargebacks', ['id'], unique=False)
    op.create_index(op.f('ix_chargebacks_merchant_id'), 'chargebacks', ['merchant_id'], unique=False)
    op.create_table('merchant_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('type_of_merchant', sa.String(), server_default='moderate', nullable=False),
    sa.Column('dba', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_profiles_id'), 'merchant_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_profiles_merchant_id'), 'merchant_profiles', ['merchant_id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('initial_setup_fee', sa.Float(), nullable=True),
    sa.Column('module1_name', sa.String(), nullable=True),
    sa.Column('module1_fee', sa.Float(), nullable=True),
    sa.Column('module2_name', sa.String(), nullable=True),
    sa.Column('module2_fee', sa.Float(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('other_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_plans_merchant_id'), 'pricing_plans', ['merchant_id'], unique=False)
    op.create_table('processor_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('processor_acquirer', sa.String(), nullable=True),
    sa.Column('avg_ticket', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processor_info_id'), 'processor_info', ['id'], unique=False)
    op.create_index(op.f('ix_processor_info_merchant_id'), 'processor_info', ['merchant_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('limit_suggestion', sa.String(), nullable=True),
    sa.Column('risk_tags', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('heat_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_scores_merchant_id'), 'scores', ['merchant_id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('merchant_signature', sa.String(), nullable=True),
    sa.Column('merchant_signed_at', sa.DateTime(), nullable=True),
    sa.Column('company_signature', sa.String(), nullable=True),
    sa.Column('company_signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_index(op.f('ix_signatures_merchant_id'), 'signatures', ['merchant_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_merchant_id'), 'webhook_logs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_merchant_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_signatures_merchant_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_scores_merchant_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_processor_info_merchant_id'), table_name='processor_info')
    op.drop_index(op.f('ix_processor_info_id'), table_name='processor_info')
    op.drop_table('processor_info')
    op.drop_index(op.f('ix_pricing_plans_merchant_id'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_merchant_profiles_merchant_id'), table_name='merchant_profiles')
    op.drop_index(op.f('ix_merchant_profiles_id'), table_name='merchant_profiles')
    op.drop_table('merchant_profiles')
    op.drop_index(op.f('ix_chargebacks_merchant_id'), table_name='chargebacks')
    op.drop_index(op.f('ix_chargebacks_id'), table_name='chargebacks')
    op.drop_table('chargebacks')
    op.drop_index(op.f('ix_ach_authorizations_merchant_id'), table_name='ach_authorizations')
    op.drop_index(op.f('ix_ach_authorizations_id'), table_name='ach_authorizations')
    op.drop_table('ach_authorizations')
    op.drop_table('plan_products')
    op.drop_index(op.f('ix_payment_gateways_user_id'), table_name='payment_gateways')
    op.drop_index(op.f('ix_payment_gateways_id'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    op.drop_index(op.f('ix_merchants_user_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
