"""mgrations_002

Revision ID: 826f0309ca43
Revises: f3e5aee40e3a
Create Date: 2025-08-20 12:07:28.351205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826f0309ca43'
down_revision: Union[str, Sequence[str], None] = 'f3e5aee40e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('business_name', sa.String(), nullable=False))
    op.add_column('merchants', sa.Column('owner_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_merchants_business_name'), 'merchants', ['business_name'], unique=False)
    op.drop_column('merchants', 'risk_tags')
    op.add_column('scores', sa.Column('limit_suggestion', sa.String(), nullable=True))
    op.add_column('scores', sa.Column('heat_score', sa.Integer(), nullable=True))
    op.alter_column('scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scores', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scores', 'decision',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scores', 'risk_tags',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('scores', 'explanation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('scores', 'risk_tags',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('scores', 'decision',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scores', 'tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('scores', 'heat_score')
    op.drop_column('scores', 'limit_suggestion')
    op.add_column('merchants', sa.Column('risk_tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_merchants_business_name'), table_name='merchants')
    op.drop_column('merchants', 'owner_name')
    op.drop_column('merchants', 'business_name')
    # ### end Alembic commands ###
