"""add type_of_merchant field to Merchant models

Revision ID: 863155985b3c
Revises: 2b3d5f58fcc5
Create Date: 2025-09-18 13:12:26.528452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863155985b3c'
down_revision: Union[str, Sequence[str], None] = '2b3d5f58fcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_profiles', sa.Column('type_of_merchant', sa.String(), server_default='moderate', nullable=False))
    op.add_column('merchants', sa.Column('type_of_merchant', sa.String(), server_default='moderate', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'type_of_merchant')
    op.drop_column('merchant_profiles', 'type_of_merchant')
    # ### end Alembic commands ###
