"""migrations_003

Revision ID: de5894e60dc3
Revises: 826f0309ca43
Create Date: 2025-08-20 19:03:10.113780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5894e60dc3'
down_revision: Union[str, Sequence[str], None] = '826f0309ca43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchants_business_name'), table_name='merchants')
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_index(op.f('ix_merchants_business_name'), 'merchants', ['business_name'], unique=False)
    # ### end Alembic commands ###
