"""migrations_005_05_OCT

Revision ID: e00df3cfe3da
Revises: 8fef4b9c703b
Create Date: 2025-10-05 02:44:01.127890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00df3cfe3da'
down_revision: Union[str, Sequence[str], None] = '8fef4b9c703b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=False),
    sa.Column('publishable_key', sa.TEXT(), nullable=False),
    sa.Column('webhook', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateways_id'), 'payment_gateways', ['id'], unique=False)
    op.create_index(op.f('ix_payment_gateways_user_id'), 'payment_gateways', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_gateways_user_id'), table_name='payment_gateways')
    op.drop_index(op.f('ix_payment_gateways_id'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
