"""mgrations_001

Revision ID: f3e5aee40e3a
Revises: 
Create Date: 2025-08-19 13:56:34.560922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e5aee40e3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legal_entity', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('mid', sa.String(), nullable=True),
    sa.Column('bin', sa.String(), nullable=True),
    sa.Column('mcc', sa.String(), nullable=True),
    sa.Column('ein', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('risk_tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_user_id'), 'merchants', ['user_id'], unique=False)
    op.create_table('ach_authorizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('routing', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('authorized_signer', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ach_authorizations_id'), 'ach_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_ach_authorizations_merchant_id'), 'ach_authorizations', ['merchant_id'], unique=False)
    op.create_table('chargebacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('chargeback_code', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargebacks_id'), 'chargebacks', ['id'], unique=False)
    op.create_index(op.f('ix_chargebacks_merchant_id'), 'chargebacks', ['merchant_id'], unique=False)
    op.create_table('merchant_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('dba', sa.String(), nullable=True),
    sa.Column('business_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_profiles_id'), 'merchant_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_profiles_merchant_id'), 'merchant_profiles', ['merchant_id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('initial_setup_fee', sa.Float(), nullable=True),
    sa.Column('module1_name', sa.String(), nullable=True),
    sa.Column('module1_fee', sa.Float(), nullable=True),
    sa.Column('module2_name', sa.String(), nullable=True),
    sa.Column('module2_fee', sa.Float(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('other_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_id'), 'pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_plans_merchant_id'), 'pricing_plans', ['merchant_id'], unique=False)
    op.create_table('processor_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('processor_acquirer', sa.String(), nullable=True),
    sa.Column('avg_ticket', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processor_info_id'), 'processor_info', ['id'], unique=False)
    op.create_index(op.f('ix_processor_info_merchant_id'), 'processor_info', ['merchant_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('risk_tags', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_scores_merchant_id'), 'scores', ['merchant_id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('merchant_signature', sa.String(), nullable=True),
    sa.Column('merchant_signed_at', sa.DateTime(), nullable=True),
    sa.Column('company_signature', sa.String(), nullable=True),
    sa.Column('company_signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_index(op.f('ix_signatures_merchant_id'), 'signatures', ['merchant_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_merchant_id'), 'webhook_logs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_merchant_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_signatures_merchant_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_scores_merchant_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_processor_info_merchant_id'), table_name='processor_info')
    op.drop_index(op.f('ix_processor_info_id'), table_name='processor_info')
    op.drop_table('processor_info')
    op.drop_index(op.f('ix_pricing_plans_merchant_id'), table_name='pricing_plans')
    op.drop_index(op.f('ix_pricing_plans_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_merchant_profiles_merchant_id'), table_name='merchant_profiles')
    op.drop_index(op.f('ix_merchant_profiles_id'), table_name='merchant_profiles')
    op.drop_table('merchant_profiles')
    op.drop_index(op.f('ix_chargebacks_merchant_id'), table_name='chargebacks')
    op.drop_index(op.f('ix_chargebacks_id'), table_name='chargebacks')
    op.drop_table('chargebacks')
    op.drop_index(op.f('ix_ach_authorizations_merchant_id'), table_name='ach_authorizations')
    op.drop_index(op.f('ix_ach_authorizations_id'), table_name='ach_authorizations')
    op.drop_table('ach_authorizations')
    op.drop_index(op.f('ix_merchants_user_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
