name: Deploy to Amazon ECR and Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${{ secrets.REPOSITORY }}" --region "${{ secrets.AWS_REGION }}" >/dev/null 2>&1 \
          || aws ecr create-repository --repository-name "${{ secrets.REPOSITORY }}" --region "${{ secrets.AWS_REGION }}" >/dev/null
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          echo "Building Docker image... ${{ steps.login-ecr.outputs.registry }}"
          docker buildx build --platform linux/arm64 -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPOSITORY }}:latest .

          echo "Tagging image for ECR... "
          # docker tag risk_core_be:latest ${{ steps.login-ecr.outputs.registry }}/risk_core_be:latest

          echo "Pushing image to ECR..."
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPOSITORY }}:latest
